# Support MirrorHR and Families Living with Epilepsy
#
# MirrorHR is an open-source, community-driven health monitoring application co-designed with patients and families. Your support helps us empower children and families fighting daily with epilepsy, providing them with real-time monitoring, symptom tracking, and a supportive community.
#
# Learn more about our mission: https://www.mirrorhr.org
# Donate to help kids and their families: https://www.fightthestroke.org/donorbox
#
# Thank you for making a difference!

custom: ["https://www.fightthestroke.org/donorboxeng"] 
