# Model Configurations
# Centralized model settings for all AI providers

default:
  provider: openai
  model_id: gpt-4o-mini
  api_key_env: OPENAI_API_KEY
  base_url: https://api.openai.com
  max_tokens: 1000
  temperature: 0.7
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  timeout: 30
  retry_attempts: 3
  cost_per_1k_tokens: 0.15

gpt-4o:
  provider: openai
  model_id: gpt-4o
  api_key_env: OPENAI_API_KEY
  base_url: https://api.openai.com
  max_tokens: 4000
  temperature: 0.7
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  timeout: 60
  retry_attempts: 3
  cost_per_1k_tokens: 2.50

gpt-4o-mini:
  provider: openai
  model_id: gpt-4o-mini
  api_key_env: OPENAI_API_KEY
  base_url: https://api.openai.com
  max_tokens: 1000
  temperature: 0.7
  top_p: 1.0
  frequency_penalty: 0.0
  presence_penalty: 0.0
  timeout: 30
  retry_attempts: 3
  cost_per_1k_tokens: 0.15

text-embedding-3-small:
  provider: openai
  model_id: text-embedding-3-small
  api_key_env: OPENAI_API_KEY
  base_url: https://api.openai.com
  max_tokens: 8192
  temperature: 0.0
  timeout: 30
  retry_attempts: 3
  cost_per_1k_tokens: 0.02

text-embedding-3-large:
  provider: openai
  model_id: text-embedding-3-large
  api_key_env: OPENAI_API_KEY
  base_url: https://api.openai.com
  max_tokens: 8192
  temperature: 0.0
  timeout: 30
  retry_attempts: 3
  cost_per_1k_tokens: 0.13

claude-3-opus:
  provider: anthropic
  model_id: claude-3-opus-20240229
  api_key_env: ANTHROPIC_API_KEY
  base_url: https://api.anthropic.com
  max_tokens: 4000
  temperature: 0.7
  top_p: 1.0
  timeout: 60
  retry_attempts: 3
  cost_per_1k_tokens: 15.00

claude-3-sonnet:
  provider: anthropic
  model_id: claude-3-sonnet-20240229
  api_key_env: ANTHROPIC_API_KEY
  base_url: https://api.anthropic.com
  max_tokens: 4000
  temperature: 0.7
  top_p: 1.0
  timeout: 45
  retry_attempts: 3
  cost_per_1k_tokens: 3.00

sonar:
  provider: perplexity
  model_id: sonar
  api_key_env: PERPLEXITY_API_KEY
  base_url: https://api.perplexity.ai
  max_tokens: 1000
  temperature: 0.1
  top_p: 0.9
  timeout: 30
  retry_attempts: 3
  cost_per_1k_tokens: 0.60